### ISSUE TITLE
Improvements and suggestions

### ISSUE THREAD

**Issue by charles-d-burton** [tfbkev/FinalProject#1]
Ok, I'm going to post links with line numbers and above them I'll post my thoughs.

This method looks undefined.  I don't see it declared anywhere in the main class.  You need to create an object or method to use it
https://github.com/tfbkev/FinalProject/blob/0ccd9708fff7a89f31ad4bcc3859ac649de02029/Main.java#L8

Do you intend to continue here?  Can the program continue here?  You have an exception but I'm not sure you should continue past this point.  
https://github.com/tfbkev/FinalProject/blob/0ccd9708fff7a89f31ad4bcc3859ac649de02029/Main.java#L13

Here I would change my exit code, you caught an exception but you're still returning an exit status of zero.  Meaning it exits cleanly despite a failure.
https://github.com/tfbkev/FinalProject/blob/0ccd9708fff7a89f31ad4bcc3859ac649de02029/Main.java#L21

Set these to their zero values or null values.  Don't declare them empty.  These should not be static also.  You want to be able to create more than one instance of them.
https://github.com/tfbkev/FinalProject/blob/0ccd9708fff7a89f31ad4bcc3859ac649de02029/BMWInventory.java#L4

Calling the class definition here is incorrect.  You can get away with it because the variables are static which is also incorrect.  To reference instance variables use `this.make = make`
https://github.com/tfbkev/FinalProject/blob/0ccd9708fff7a89f31ad4bcc3859ac649de02029/BMWInventory.java#L11
Same....
https://github.com/tfbkev/FinalProject/blob/0ccd9708fff7a89f31ad4bcc3859ac649de02029/BMWInventory.java#L23

Be clear, use `this.model`
https://github.com/tfbkev/FinalProject/blob/0ccd9708fff7a89f31ad4bcc3859ac649de02029/BMWInventory.java#L27

I assume this is what you want to us to search through the code that you're calling from main.  The issue with calling this from main is that you haven't declared an instance of this objecte in main.  You'll need to make none of this static and do 
```java
BMWIventory inventory = new BMWInventory();
```
or something similar

https://github.com/tfbkev/FinalProject/blob/0ccd9708fff7a89f31ad4bcc3859ac649de02029/BMWInventory.java#L58

**Comment by tfbkev** [comment]
> Ok, I'm going to post links with line numbers and above them I'll post my thoughs.
> 
> This method looks undefined. I don't see it declared anywhere in the main class. You need to create an object or method to use it
> 
> https://github.com/tfbkev/FinalProject/blob/0ccd9708fff7a89f31ad4bcc3859ac649de02029/Main.java#L8
> 
> Do you intend to continue here? Can the program continue here? You have an exception but I'm not sure you should continue past this point.
> 
> https://github.com/tfbkev/FinalProject/blob/0ccd9708fff7a89f31ad4bcc3859ac649de02029/Main.java#L13
> 
> Here I would change my exit code, you caught an exception but you're still returning an exit status of zero. Meaning it exits cleanly despite a failure.
> 
> https://github.com/tfbkev/FinalProject/blob/0ccd9708fff7a89f31ad4bcc3859ac649de02029/Main.java#L21
> 
> Set these to their zero values or null values. Don't declare them empty. These should not be static also. You want to be able to create more than one instance of them.
> 
> https://github.com/tfbkev/FinalProject/blob/0ccd9708fff7a89f31ad4bcc3859ac649de02029/BMWInventory.java#L4
> 
> Calling the class definition here is incorrect. You can get away with it because the variables are static which is also incorrect. To reference instance variables use `this.make = make`
> 
> https://github.com/tfbkev/FinalProject/blob/0ccd9708fff7a89f31ad4bcc3859ac649de02029/BMWInventory.java#L11
> 
> 
> Same....
> https://github.com/tfbkev/FinalProject/blob/0ccd9708fff7a89f31ad4bcc3859ac649de02029/BMWInventory.java#L23
> 
> Be clear, use `this.model`
> 
> https://github.com/tfbkev/FinalProject/blob/0ccd9708fff7a89f31ad4bcc3859ac649de02029/BMWInventory.java#L27
> 
> I assume this is what you want to us to search through the code that you're calling from main. The issue with calling this from main is that you haven't declared an instance of this objecte in main. You'll need to make none of this static and do
> 
> ```java
> BMWIventory inventory = new BMWInventory();
> ```
> 
> or something similar
> 
> https://github.com/tfbkev/FinalProject/blob/0ccd9708fff7a89f31ad4bcc3859ac649de02029/BMWInventory.java#L58

**Comment by tfbkev** [comment]
> Ok, I'm going to post links with line numbers and above them I'll post my thoughs.
> 
> This method looks undefined. I don't see it declared anywhere in the main class. You need to create an object or method to use it

In BMWinventory tosearch is defined why would you defined again in the main? Wouldnt main be able to read it and understand its a declared already? 
> 
> https://github.com/tfbkev/FinalProject/blob/0ccd9708fff7a89f31ad4bcc3859ac649de02029/Main.java#L8
> 
> Do you intend to continue here? Can the program continue here? You have an exception but I'm not sure you should continue past this point.
> 
> https://github.com/tfbkev/FinalProject/blob/0ccd9708fff7a89f31ad4bcc3859ac649de02029/Main.java#L13
> 
> Here I would change my exit code, you caught an exception but you're still returning an exit status of zero. Meaning it exits cleanly despite a failure.
Not sure what this means
> 
> https://github.com/tfbkev/FinalProject/blob/0ccd9708fff7a89f31ad4bcc3859ac649de02029/Main.java#L21
> 
> Set these to their zero values or null values. Don't declare them empty. These should not be static also. You want to be able to create more than one instance of them.
> 
All set with this and has been updated to reflect
> https://github.com/tfbkev/FinalProject/blob/0ccd9708fff7a89f31ad4bcc3859ac649de02029/BMWInventory.java#L4
> 
> Calling the class definition here is incorrect. You can get away with it because the variables are static which is also incorrect. To reference instance variables use `this.make = make`
> 
All set with this and has been updated to reflect
> https://github.com/tfbkev/FinalProject/blob/0ccd9708fff7a89f31ad4bcc3859ac649de02029/BMWInventory.java#L11
> 
> 
> Same....
> https://github.com/tfbkev/FinalProject/blob/0ccd9708fff7a89f31ad4bcc3859ac649de02029/BMWInventory.java#L23
> All set with this and has been updated to reflect
> Be clear, use `this.model`
> 
> https://github.com/tfbkev/FinalProject/blob/0ccd9708fff7a89f31ad4bcc3859ac649de02029/BMWInventory.java#L27
> 
> I assume this is what you want to us to search through the code that you're calling from main. The issue with calling this from main is that you haven't declared an instance of this objecte in main. You'll need to make none of this static and do
> 
> ```java
> BMWIventory inventory = new BMWInventory();
> ```
> Not understanding. I thought the whole point of creating API was so that you didn't have to define in the main?
> or something similar
> 
> https://github.com/tfbkev/FinalProject/blob/0ccd9708fff7a89f31ad4bcc3859ac649de02029/BMWInventory.java#L58
